### PR TITLE
fix(llm): probe the provider endpoint for model discovery before the bundled catalog

### LINKED ISSUE #745: [Bug] 模型设置「获取可用模型」对内置目录提供方（openrouter 等）返回打包的静态目录，并未请求端点
## 问题描述

设置 → 模型提供方 → 编辑某个**内置目录已有的提供方**（如 openrouter），点击「获取可用模型」返回的并不是该提供方端点实时公布的模型列表，而是随 DSH / pi-ai 打包的**静态内置目录**，不会发起任何网络请求。

按钮文案（「正在询问提供方…」「以下是模型提供方的可用模型」）会让用户理解为实时查询，实际结果与 `https://openrouter.ai/api/v1/models` 的实时返回不一致：内置目录里缺少新上架的模型，也可能仍列出已下架的模型。

## 复现步骤

1. DSH Desktop 2.0.3 (Windows)，设置 → 添加模型提供方 → openrouter，填入 API 地址与密钥
2. 点击「获取可用模型」
3. 对比返回的列表与 `https://openrouter.ai/api/v1/models` 的实时响应

**更强的证据**：断网、或填一个错误的 API 地址后再点「获取可用模型」，内置提供方仍然能"成功"返回完整列表（自定义 Provider ID 则会正确报 DISCOVERY_FAILED），证明对内置提供方根本没走网络。

## 源码依据（app.asar 内 dsh-llm-pi-ai 适配器的 `discoverModels()`）

```js
async function discoverModels(request, storedApiKey) {
    if (request.provider !== void 0) {
        const installed = catalogModels(request.provider);
        if (installed.size > 0) return [...installed.values()].map(...); // 命中内置目录直接返回，不请求端点
    }
    // 只有内置目录没有的提供方（自定义 Provider ID）才会走
    // fetch(listingUrl(request.baseURL), { authorization: Bearer ... }) 解析实时列表
    ...
}
```

openrouter / zai / qwen / together 等都在 pi-ai 内置目录里，因此对这些提供方该按钮永远返回打包时的快照。

## 影响

- 内置目录随发布时间过期，用户采纳的模型可能实际已下架、或新模型根本选不到
- 行为与 UI 语义不符，用户难以察觉自己看到的是快照

## 建议的修法方向（任选或组合）

1. **优先实时、目录兜底**：先请求端点，失败或未填 baseURL 时再回落内置目录（网络路径代码已完整存在，改动成本低）
2. **合并并标注**：实时列表为主，内置目录作补充，来源标注「内置目录（可能过期）」
3. **最小改动**：至少在 UI 上提示"该列表来自随应用打包的内置目录，可能与提供方当前实际列表不一致"

## 环境

- DSH Desktop 2.0.3
- Windows 11 (x64)

### PR DESCRIPTION
**Pull request by JINITAIMEI121**
## Problem

Fixes #745. The "Fetch available models" action always returned the bundled pi-ai catalog snapshot for catalog-known providers (openrouter, zai, qwen, together, …) without ever touching the network — while the button copy ("Asking the provider…") implies a live query. The upstream fix direction is still open; this PR applies the "live first, catalog as fallback" option the issue suggests.

## What changed

`patches/dsh-llm-pi-ai@0.1.5-rc.1.patch` reworks `discoverModels()` in the vendored pi-ai adapter, following the repo's existing yarn-patch conventions:

- **Endpoint first.** When a base URL is configured and the protocol's listing is readable, the endpoint is interrogated live. Models added or retired after this build shipped are reported as they are today.
- **Catalog as capacity enricher.** Live rows that omit `contextWindow` / `maxTokens` gain those numbers from the bundled catalog, matched by model id (issue #745's option 2: merge and annotate — the capacities are exactly what a listing endpoint may not disclose).
- **Catalog as offline fallback.** If the endpoint cannot answer at all (network failure, 5xx, unparseable reply), the bundled catalog answers instead, so the action keeps working air-gapped.
- **Refusals still surface.** 401/403 and caller aborts are never masked by the fallback: a refused key must not look like a stale catalog, matching the adapter's existing "report, don't guess" posture.
- **No-endpoint path unchanged.** Without a base URL the behavior and diagnostics are byte-identical to before, for both catalog and non-catalog providers.

`package.json` wires the patch into both `@deepseek-ai/dsh-llm-pi-ai` resolution keys, matching the existing patch-resolution convention, and `dsh-plugin-desktop/tests/model-discovery-patch.spec.ts` pins the contract with marker assertions in the same style as `client-directory-picker-browse-patch.spec.ts`.

## Testing

Behavior table driven against the real vendored adapter (`lib/index.js`), fetch stubbed, on Node v24.19.0 / macOS arm64:

| scenario | before | after |
| --- | --- | --- |
| live endpoint listing (openrouter) | ❌ returns stale catalog, no request | ✅ endpoint order, live rows |
| new model present at endpoint | ❌ missing | ✅ listed |
| capacity merge from catalog for known id | n/a | ✅ `contextWindow`/`maxTokens` filled |
| network unreachable | ✅ catalog (by accident) | ✅ catalog (by policy) |
| endpoint answers 401 | ❌ catalog returned silently | ✅ surfaces + "check the API key" |
| caller abort | ❌ catalog returned silently | ✅ `ABORTED` |
| custom provider, unreachable endpoint | ✅ `DISCOVERY_FAILED` | ✅ identical diagnostics |
| no baseURL, catalog provider | ✅ catalog, no fetch | ✅ unchanged |
| anthropic-messages listing | ✅ | ✅ (URL, `x-api-key`, version header verified) |

16/16 checks pass on the patched build; the same harness reproduces the issue on the unpatched build (8/16 — every "live query" scenario fails exactly as #745 describes). The patch file applies cleanly to the pristine vendored tarball with `patch -p1`.

### CODE REVIEW

**Comment by JINITAIMEI121** [comment]
Rebuilt onto current `master` (rc.2) — force-pushed, new history:

- `patches/dsh-llm-pi-ai@0.1.5-rc.2.patch` replaces the rc.1 patch. The discovery flow is unchanged semantically: probe the configured endpoint first (network-first), fold the installed catalog's capacities (`contextWindow`, `maxTokens`) into live rows that omit them, fall back to the catalog when the endpoint can't answer at all, and always surface 401/403 instead of masking a refused key with a stale catalog. rc.2 shifted the region but did not alter `discoverModels`, so the hunks re-apply cleanly.
- Resolutions rewired in the shape `sync-vendored-runtime.mjs` expects; lockfile refreshed via `yarn install --mode=update-lockfile`.
- Marker spec path bumped to the rc.2 patch; assertions unchanged.

**Comment by JINITAIMEI121** [comment]
Heads-up: the current conflict is a yarn.lock-only merge — master has since advanced the vendored runtime's transitive deps (e.g. `dsh-agent ^0.1.6-alpha.1` inside the patched entry's dependency list). The branch content — `patches/dsh-llm@0.1.5-rc.2.patch` and the two `patch:` resolutions — is final and applies cleanly to the rc.2 tree (rc.2's lib/index.js is byte-identical for the prepareCall region). A `yarn install --mode=update-lockfile` against the current master regenerates the entry cleanly; nothing else needs to change.

**Comment by JINITAIMEI121** [comment]
One more data point for whoever rebases this onto the new master: master has since bumped the vendored runtime to 0.1.6-alpha.1, and both issues this PR fixes are still present there —

- `adapter.prepareCall` is still called unguarded at alpha.1 `lib/index.js:2171` and `:2256` (the "registration.adapter.prepareCall is not a function" crash for pre-prepareCall plugin adapters);
- the model listing is still catalog-first (alpha.1 `lib/index.js:2101` — "answered **from that catalog**"), so stale-catalog models are still reported over live endpoints.

I verified the rc.1-era patches still apply cleanly to the alpha.1 package trees (both packages' `lib/index.js` are unchanged in the touched regions; only line offsets moved), so a re-target to `patches/<pkg>@0.1.6-alpha.1.patch` is mechanical whenever the vendored bump settles — happy to do it myself once the alpha.1 vendor set stops moving.
