### PR TITLE
fix(llm): tolerate adapters without prepareCall when preparing calls

### LINKED ISSUE #744: 本轮运行失败registration.adapter.prepareCall is not a function
### Existing reports / 提交前查重

- [x] I searched existing issues and did not find the same problem / 我已搜索现有 Issue，没有发现相同问题

### Affected area / 涉及区域

Startup or installation / 启动或安装

### Operating system / 操作系统

Windows 11 x64

### Installation method / 安装方式

Windows installer / Windows 安装包

### DSH Desktop version / DSH Desktop 版本

2.0.4

### DSH runtime version / DSH 运行时版本

Unknown

### Profile type / Profile 类型

Default or built-in Profile / 默认或内置 Profile

### Third-party plugins / 第三方插件

dsh-vision-router 1.6.0

### Fresh Profile comparison / 全新 Profile 对照结果

Still reproduces in a fresh Profile / 全新 Profile 仍可复现

### What happened? / 实际发生了什么？

Image

### Reproduction steps / 复现步骤

创建一个新项目
问话

### Expected behavior / 预期结果

开始干活

### Reproduction frequency / 复现频率

Every time / 每次都能复现

### Logs or error details / 日志或错误信息

[diagnostics-1788066137322-decbe43a-489c-46a1-b7ac-507b0c7b034f.zip](https://github.com/user-attachments/files/31608300/diagnostics-1788066137322-decbe43a-489c-46a1-b7ac-507b0c7b034f.zip)

### Screenshots or recordings / 截图或录屏

已提供

### Last known working version / 最后正常版本

2.0.3

### Additional context / 补充信息

_No response_

### Sensitive information / 敏感信息

- [x] I removed API keys, tokens, account details, and other sensitive data from my attachments / 我已从附件中移除 API Key、Token、账号信息等敏感内容

### PR DESCRIPTION
**Pull request by JINITAIMEI121**
## Problem

Fixes #744 (`registration.adapter.prepareCall is not a function`). A third-party plugin adapter written against the pre-`prepareCall` contract — a plain object exposing `providerInfo`, `providerRetryPolicy`, `resolveModel`, and `stream`, but no `prepareCall` — registers fine but crashes the first time the runtime prepares a call. The reporter's repro (dsh-vision-router 1.6.0 on 2.0.4, worked on 2.0.3, fails every round with a fresh Profile) matches exactly.

## What changed

`patches/dsh-llm@0.1.5-rc.1.patch` adds one module-level helper, `adapterPrepareCall(adapter, provider, model, signal)`, and routes both runtime call sites (`prepareCall(config, signal)` and the unprepared branch of `adapterStream`) through it:

- **Modern adapters are untouched.** If `adapter.prepareCall` is a function, the helper is a pure pass-through — same call, same binding, same generation semantics.
- **Legacy adapters get the `LlmAdapter` default, synthesized externally.** That default is precisely `model: await this.resolveModel(provider, model, signal)` plus `stream: (options) => this.stream(options)`; the helper reproduces it for plain-object adapters, and falls back to an identity model when even `resolveModel` is absent.
- **No contract change.** Registration-time validation (`providerInfo`, `providerRetryPolicy`) is untouched; the patch only affects call preparation, which is where #744 fails.

`package.json` wires the patch into both `@deepseek-ai/dsh-llm` resolution keys, following the existing patch-resolution convention, and `dsh-plugin-desktop/tests/adapter-prepare-call-compat-patch.spec.ts` pins the contract with marker assertions in the same style as the other patch specs.

## Testing

The real vendored `@deepseek-ai/dsh-llm` loaded with stubbed host deps; `LlmRuntime` constructed against a stub `ctx` (events, logger, effect, waterfall); adapters registered through the real `registerAdapter` path. Node v24.19.0, macOS arm64.

| scenario | before | after |
| --- | --- | --- |
| legacy adapter (no `prepareCall`) prepare | ❌ `TypeError: registration.adapter.prepareCall is not a function` at `lib/index.js:2147` — the exact #744 error | ✅ prepared, dispatched |
| legacy `resolveModel` consulted | ❌ never reached | ✅ called with `(provider, model, signal)` |
| dispatch bound to legacy `stream` | ❌ | ✅ chunks flow (`legacy:m2`) |
| minimal adapter (no `resolveModel` either) | ❌ | ✅ identity model fallback, still streams |
| modern adapter with its own `prepareCall` | ✅ | ✅ pass-through — `prepareCall` invoked, not the fallback |
| `LlmAdapter` subclass (inherited default) | ✅ | ✅ intact |

8/8 checks pass on the patched build; the same harness on the unpatched build throws the #744 `TypeError` before any assertion can run. The patch file applies cleanly to the pristine vendored tarball with `patch -p1`.

### CODE REVIEW

**Comment by JINITAIMEI121** [comment]
Rebuilt onto current `master` (rc.2) — force-pushed, new history:

- `patches/dsh-llm@0.1.5-rc.2.patch` replaces the rc.1 patch: rc.2's `lib/index.js` only shifted line numbers around `prepareCall`, so the change is identical — `adapterPrepareCall()` feature-detects before both runtime call sites and synthesizes the `LlmAdapter` default (resolveModel + stream) for plain-object plugin adapters. Issue #744's `registration.adapter.prepareCall is not a function` is still open against rc.2, and the rc.2 tarball still has bare `registration.adapter.prepareCall(...)` at both sites.
- Resolutions rewired in the exact shape `sync-vendored-runtime.mjs` expects (both `@npm:0.1.5-rc.2` and `@npm:^0.1.5-rc.2` keys), lockfile refreshed with `yarn install --mode=update-lockfile`.
- The marker spec now reads the rc.2 patch path; its assertions are unchanged.

**Comment by JINITAIMEI121** [comment]
Heads-up: the current conflict is a yarn.lock-only merge — master has since advanced the vendored runtime's transitive deps (e.g. `dsh-agent ^0.1.6-alpha.1` inside the patched entry's dependency list). The branch content — `patches/dsh-llm@0.1.5-rc.2.patch` and the two `patch:` resolutions — is final and applies cleanly to the rc.2 tree (rc.2's lib/index.js is byte-identical for the prepareCall region). A `yarn install --mode=update-lockfile` against the current master regenerates the entry cleanly; nothing else needs to change.

**Comment by JINITAIMEI121** [comment]
One more data point for whoever rebases this onto the new master: master has since bumped the vendored runtime to 0.1.6-alpha.1, and both issues this PR fixes are still present there —

- `adapter.prepareCall` is still called unguarded at alpha.1 `lib/index.js:2171` and `:2256` (the "registration.adapter.prepareCall is not a function" crash for pre-prepareCall plugin adapters);
- the model listing is still catalog-first (alpha.1 `lib/index.js:2101` — "answered **from that catalog**"), so stale-catalog models are still reported over live endpoints.

I verified the rc.1-era patches still apply cleanly to the alpha.1 package trees (both packages' `lib/index.js` are unchanged in the touched regions; only line offsets moved), so a re-target to `patches/<pkg>@0.1.6-alpha.1.patch` is mechanical whenever the vendored bump settles — happy to do it myself once the alpha.1 vendor set stops moving.
